# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: mongo-lambda

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: ap-south-1

# The `functions` block defines what code to deploy
functions:
  execute:
    handler: handler.execute
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: execute
          method: post
          cors: true
